In [50]:
import pandas as pd
o_hqc_d_bmy_result=pd.read_csv('o_hqc_d_bmy_result.csv',index_col=0)
o_hqc_d_bmy_result.head()

,ds,o_adcode,d_adcode,source_grid,target_grid,o_x,o_y,d_x,d_y,o_time,...,uv,confidence,geometry,new_index_right,fid,id_left,name_left,index_right,id_right,name_right
1758047,20230919,610115,610115,1800192_0801517,1800262_0801544,109.208939,34.365887,109.284912,34.390190,09:30,...,1,高,POINT (109.284912 34.39019),0,1.0,1.0,huaqingchi,0,NaN,binmayong
1759312,20230919,610115,610115,1800194_0801515,1800257_0801537,109.211105,34.364086,109.279488,34.383888,10:30,...,1,高,POINT (109.279488 34.383888),0,1.0,1.0,huaqingchi,0,NaN,binmayong
1759338,20230919,610115,610115,1800194_0801516,1800256_0801537,109.211105,34.364986,109.278397,34.383888,09:30,...,1,高,POINT (109.278397 34.383888),0,1.0,1.0,huaqingchi,0,NaN,binmayong
1759339,20230919,610115,610115,1800194_0801516,1800257_0801537,109.211105,34.364986,109.279488,34.383888,07:30,...,1,高,POINT (109.279488 34.383888),0,1.0,1.0,huaqingchi,0,NaN,binmayong
1759340,20230919,610115,610115,1800194_0801516,1800257_0801537,109.211105,34.364986,109.279488,34.383888,12:30,...,1,高,POINT (109.279488 34.383888),0,1.0,1.0,huaqingchi,0,NaN,binmayong

In [51]:
# 获取所有列名的列表
column_names = o_hqc_d_bmy_result.columns.tolist()

# 找到要删除的列的索引
start_index = column_names.index('o_adcode')
end_index = column_names.index('d_y')

# 创建一个要删除的列名列表
columns_to_drop = column_names[start_index:end_index + 1]#取出的一个列表切片
# 删除这些列
o_hqc_d_bmy = o_hqc_d_bmy_result.drop(columns=columns_to_drop, inplace=False)
o_hqc_d_bmy.head()

,ds,o_time,d_time,travel_mode,duration,distance,dir,uv,confidence,geometry,new_index_right,fid,id_left,name_left,index_right,id_right,name_right
1758047,20230919,09:30,14:45,骑步行,322.0,7.5,2,1,高,POINT (109.284912 34.39019),0,1.0,1.0,huaqingchi,0,NaN,binmayong
1759312,20230919,10:30,13:00,地铁,149.0,6.7,2,1,高,POINT (109.279488 34.383888),0,1.0,1.0,huaqingchi,0,NaN,binmayong
1759338,20230919,09:30,10:00,地铁,39.0,6.5,2,1,高,POINT (109.278397 34.383888),0,1.0,1.0,huaqingchi,0,NaN,binmayong
1759339,20230919,07:30,09:00,骑步行,94.0,6.6,2,1,高,POINT (109.279488 34.383888),0,1.0,1.0,huaqingchi,0,NaN,binmayong
1759340,20230919,12:30,14:30,骑步行,119.0,6.6,2,1,高,POINT (109.279488 34.383888),0,1.0,1.0,huaqingchi,0,NaN,binmayong

In [52]:
new_column_value = '华清池'
o_hqc_d_bmy.insert(1, '起点POI', new_column_value)

new_column_value = '兵马俑'
o_hqc_d_bmy.insert(2, '终点POI', new_column_value)
o_hqc_d_bmy.head()

,ds,起点POI,终点POI,o_time,d_time,travel_mode,duration,distance,dir,uv,confidence,geometry,new_index_right,fid,id_left,name_left,index_right,id_right,name_right
1758047,20230919,华清池,兵马俑,09:30,14:45,骑步行,322.0,7.5,2,1,高,POINT (109.284912 34.39019),0,1.0,1.0,huaqingchi,0,NaN,binmayong
1759312,20230919,华清池,兵马俑,10:30,13:00,地铁,149.0,6.7,2,1,高,POINT (109.279488 34.383888),0,1.0,1.0,huaqingchi,0,NaN,binmayong
1759338,20230919,华清池,兵马俑,09:30,10:00,地铁,39.0,6.5,2,1,高,POINT (109.278397 34.383888),0,1.0,1.0,huaqingchi,0,NaN,binmayong
1759339,20230919,华清池,兵马俑,07:30,09:00,骑步行,94.0,6.6,2,1,高,POINT (109.279488 34.383888),0,1.0,1.0,huaqingchi,0,NaN,binmayong
1759340,20230919,华清池,兵马俑,12:30,14:30,骑步行,119.0,6.6,2,1,高,POINT (109.279488 34.383888),0,1.0,1.0,huaqingchi,0,NaN,binmayong

In [53]:
# 获取所有列名的列表
column_names = o_hqc_d_bmy.columns.tolist()

# 找到要删除的列的索引
start_index = column_names.index('geometry')
end_index = column_names.index('name_right')

# 创建一个要删除的列名列表
columns_to_drop = column_names[start_index:end_index + 1]#取出的一个列表切片
# 删除这些列
o_hqc_d_bmy = o_hqc_d_bmy.drop(columns=columns_to_drop, inplace=False)
o_hqc_d_bmy.head()

,ds,起点POI,终点POI,o_time,d_time,travel_mode,duration,distance,dir,uv,confidence
1758047,20230919,华清池,兵马俑,09:30,14:45,骑步行,322.0,7.5,2,1,高
1759312,20230919,华清池,兵马俑,10:30,13:00,地铁,149.0,6.7,2,1,高
1759338,20230919,华清池,兵马俑,09:30,10:00,地铁,39.0,6.5,2,1,高
1759339,20230919,华清池,兵马俑,07:30,09:00,骑步行,94.0,6.6,2,1,高
1759340,20230919,华清池,兵马俑,12:30,14:30,骑步行,119.0,6.6,2,1,高

In [54]:
o_hqc_d_bmy.columns=['日期','起点POI','终点POI','出发时间','到达时间','出行方式','出行时间','出行距离','方向','人数','置信度']
del o_hqc_d_bmy['方向']
o_hqc_d_bmy

                日期 起点POI 终点POI   出发时间   到达时间 出行方式   出行时间  出行距离  人数 置信度
1758047   20230919   华清池   兵马俑  09:30  14:45  骑步行  322.0   7.5   1   高
1759312   20230919   华清池   兵马俑  10:30  13:00   地铁  149.0   6.7   1   高
1759338   20230919   华清池   兵马俑  09:30  10:00   地铁   39.0   6.5   1   高
1759339   20230919   华清池   兵马俑  07:30  09:00  骑步行   94.0   6.6   1   高
1759340   20230919   华清池   兵马俑  12:30  14:30  骑步行  119.0   6.6   1   高
...            ...   ...   ...    ...    ...  ...    ...   ...  ..  ..
23616638  20230919   华清池   兵马俑  10:00  12:00  骑步行  112.0   6.3   1   高
23616639  20230919   华清池   兵马俑  09:45  10:15   地铁   38.0   6.4   1   高
23616674  20230919   华清池   兵马俑  12:00  12:15   驾车   19.0   7.3   1   高
23617470  20230919   华清池   兵马俑  10:00  10:15   驾车   14.0   7.2   1   高
23617482  20230919   华清池   兵马俑  09:45  10:15   地铁   35.0   6.7   1   高

[450 rows x 10 columns]

In [55]:
o_hqc_d_bmy=o_hqc_d_bmy.reset_index()
del o_hqc_d_bmy['index']
o_hqc_d_bmy

           日期 起点POI 终点POI   出发时间   到达时间 出行方式   出行时间  出行距离  人数 置信度
0    20230919   华清池   兵马俑  09:30  14:45  骑步行  322.0   7.5   1   高
1    20230919   华清池   兵马俑  10:30  13:00   地铁  149.0   6.7   1   高
2    20230919   华清池   兵马俑  09:30  10:00   地铁   39.0   6.5   1   高
3    20230919   华清池   兵马俑  07:30  09:00  骑步行   94.0   6.6   1   高
4    20230919   华清池   兵马俑  12:30  14:30  骑步行  119.0   6.6   1   高
..        ...   ...   ...    ...    ...  ...    ...   ...  ..  ..
445  20230919   华清池   兵马俑  10:00  12:00  骑步行  112.0   6.3   1   高
446  20230919   华清池   兵马俑  09:45  10:15   地铁   38.0   6.4   1   高
447  20230919   华清池   兵马俑  12:00  12:15   驾车   19.0   7.3   1   高
448  20230919   华清池   兵马俑  10:00  10:15   驾车   14.0   7.2   1   高
449  20230919   华清池   兵马俑  09:45  10:15   地铁   35.0   6.7   1   高

[450 rows x 10 columns]

In [56]:
o_hqc_d_bmy.to_csv('从华清池到兵马俑.csv')